added: add modal component
privy-open-source/design-system pull request #108
Opened 2022-06-09 03:29 UTC by avriq

2022-06-14 04:20 UTC, adenvt requested changes
@avriq revisi pack :')

2022-06-14 04:20 UTC, adenvt commented on components/modal/Modal.spec.ts
> +  expect(modal).toHaveAttribute('style', 'display: none;')
@avriq bisa pake `expect(modal).not.toBeVisible()` buat ngecek element hidden atau gak

2022-06-22 23:06 UTC, avriq commented on components/modal/Modal.vue
>      }
woalaa.. siuup :)))

2022-06-24 11:48 UTC, adenvt commented on components/overlay/Overlay.vue
delete aj pak @avriq

2022-06-27 04:29 UTC, adenvt approved these changes

2022-06-27 04:33 UTC, merged