Feat/foundation typography
privy-open-source/design-system pull request #389
Opened 2023-01-26 12:20 UTC by avriq

2023-01-27 03:25 UTC, adenvt requested changes
@avriq Revice dikit

2023-01-27 03:25 UTC, adenvt commented on src/components/text/index.md
> +</preview>
@avriq kayak'e bagus hyperlink ngecek prop href, jadi selama prop href'nya diisi, dia mode hyperlink.

Menurutmu gimana pack??

2023-01-30 08:03 UTC, avriq commented on src/components/text/index.md
> +</preview>
@adenvt wah betul juga, setuju lord. lebih simple jatuhnya

2023-01-30 08:45 UTC, avriq commented on src/components/text/index.md
> +</preview>
@adenvt updated lord

2023-02-01 00:15 UTC, adenvt approved these changes
Mantap :+1:

2023-02-01 00:15 UTC, merged